meta:
  url: https://ppt.scubot.com
  title: 东风ppt
  description: 组会记录
  siteName: scubot ppt
  sns: ['github']
slide:
  loop: false
  ui:
    sidebar: true
    vertical: false
    pagination: bullets # bullets | progressbar | fraction
    effect: fade # fade | cube | flip
  code:
    # https://prismjs.com/
    plugins: []
    theme: default # coy | dark | funky | okaidia | solarizedlight | tomorrow | twilight
